# Generated by Django 3.0.5 on 2020-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='no desc', max_length=4000),
            preserve_default=False,
        ),
    ]
