# Generated by Django 3.0.5 on 2020-10-29 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 18, 27, 13, 448252, tzinfo=utc)),
        ),
    ]
