# Generated by Django 3.0.5 on 2020-11-13 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 17, 46, 686689, tzinfo=utc)),
        ),
    ]
